import { DB, _allLoreSets, _allStories, _allChats } from '../core/db.js';

export const state = {
  inputBox: null,
  sidebarInputBox: null,
  allStories: [],
  visibleLimit: 3,
  selectedChatCharacters: [],
  _isHashNavigation: false,
  selectedCreationMode: 'AUTO',
  selectedDeductionLevel: 'Standard',
  dlPopupTimeout: null,
  dlPopupShowTimeout: null,
  isDlPopupClicked: false,
  collectionsData: {},
  currentCollectionId: null,
  currentLoreSetId: null,
  currentData: { title: '', desc: '', stories: [], chats: [], kg: { nodes: [], links: [] } },
  kg: null,
  viewMode: 'graph',
  activeSelectedNode: null,
  storyDialogues: {},
  activeStoryDialogue: [],
  activeStoryName: "",
  sidebarCategoryIndex: 0,
  isSidebarCollapsed: false,
  sidebarDialogueHistories: {},
  currentSidebarStoryName: null,
  editDialogueHistory: [],
  _currentSidebarSessionSource: null,
  _currentSidebarSessionId: null,
  isUserLoggedIn: false,
  editViewMode: 'list',
  editActiveCategory: 'worldview',
  editKG: null,
  isEditingIndependentStory: false,
  activeEditingStoryId: null,
  _modalKG: null,
};

export { DB, _allLoreSets, _allStories, _allChats };
