import { DB, _allLoreSets, _allStories, _allChats } from '../core/db.js';

export const state = {
  inputBox: null,
  sidebarInputBox: null,
  allStories: [],
  visibleLimit: 3,
  selectedChatCharacters: [],
  _isHashNavigation: false,
  selectedCreationMode: 'AUTO',
  selectedDeductionLevel: 'Standard',
  dlPopupTimeout: null,
  dlPopupShowTimeout: null,
  isDlPopupClicked: false,
  loresetData: {},
  currentLoreSetId: null,
  currentData: { title: '', desc: '', stories: [], chats: [], kg: { nodes: [], links: [] } },
  kg: null,
  viewMode: 'graph',
  activeSelectedNode: null,
  storySessions: {},
  activeStoryMessages: [],
  activeStoryId: "",
  sidebarCategoryIndex: 0,
  isSidebarCollapsed: false,
  sidebarSessions: {},
  currentSidebarStoryId: null,
  editorSessions: [],
  _currentSidebarChatSource: null,
  _currentSidebarChatId: null,
  isUserLoggedIn: false,
  editViewMode: 'list',
  editActiveCategory: 'worldview',
  editKG: null,
  isEditingStandalone: false,
  _modalKG: null,
};

export { DB, _allLoreSets, _allStories, _allChats };
